### ISSUE TITLE
missing util/conv4d.py?

### ISSUE THREAD

**Issue by tawnkramer** [ignacio-rocco/weakalign#1]
trying out demo.py, getting an error:

```
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from model.cnn_geometric_model import CNNGeometric, TwoStageCNNGeometric
  File "/Users/tkramer/projects/weakalign/model/cnn_geometric_model.py", line 9, in <module>
    from util.conv4d import Conv4d, Linear4d
ModuleNotFoundError: No module named 'util.conv4d'
```

**Comment by aymenx17** [comment]
Thanks for sharing the good. I'm getting the same error

**Comment by cemoody** [comment]
Thank you for sharing! Can you add & recommit the file? Thanks!

**Comment by ignacio-rocco** [comment]
Hi, thanks for reporting this.

I have deleted the references to this legacy file.

I don't have a computer to try the code now, but it should work :)
