### ISSUE TITLE
Questions about affTpsTnf() function in Demo.py 

### ISSUE THREAD

**Issue by nbei** [ignacio-rocco/weakalign#15]
Thanks for your sharing the code for this project. I just have a question about the implementation of the affTpsTnf function in Demo.py.

```python
def affTpsTnf(source_image, theta_aff, theta_aff_tps, use_cuda=use_cuda):
    tpstnf = GeometricTnf(geometric_model = 'tps',use_cuda=use_cuda)
    sampling_grid = tpstnf(image_batch=source_image,
                           theta_batch=theta_aff_tps,
                           return_sampling_grid=True)[1]
    X = sampling_grid[:,:,:,0].unsqueeze(3)
    Y = sampling_grid[:,:,:,1].unsqueeze(3)
    Xp = X*theta_aff[:,0].unsqueeze(1).unsqueeze(2)+Y*theta_aff[:,1].unsqueeze(1).unsqueeze(2)+theta_aff[:,2].unsqueeze(1).unsqueeze(2)
    Yp = X*theta_aff[:,3].unsqueeze(1).unsqueeze(2)+Y*theta_aff[:,4].unsqueeze(1).unsqueeze(2)+theta_aff[:,5].unsqueeze(1).unsqueeze(2)
    sg = torch.cat((Xp,Yp),3)
    warped_image_batch = F.grid_sample(source_image, sg)

    return warped_image_batch
```

In this implementation, you first use the TPS and then the affine transformation. However, when training the network, the model adopt the affine transformation before the TPS operation. I'm just a little bit confused about it and is it right?

I have checekd the CNNGeo in your another [repo](https://github.com/ignacio-rocco/cnngeometric_pytorch/blob/master/demo.py). 

```python
theta_aff_tps = model_tps({'source_image': warped_image_aff, 'target_image': batch['target_image']})
warped_image_aff_tps = tpsTnf(warped_image_aff, theta_aff_tps)
```

In this implementation, you first do the affine transformation and then follow the TPS transformation. Are there any differences between these two implementions?

Looking forward to your reply.

**Comment by ignacio-rocco** [comment]
Hi Rui,

Indeed the approaches are different. The one on the weakalign repo is first
computing the composed sampling grid, and then sampling on the image; while
the approach on the CNNGeo repo is first *warping* the image using an
affine transformation, and then *warping again* using a TPS transformation.
The only difference between the final result is with respect to the edges,
the approach in weakalign is superior and should produce less "black edges".

I hope this clarifies a bit.
Ignacio

**Comment by nbei** [comment]
Hi Ignacio,

Thanks for your prompt reply and your clarification actually helps me. However, a further confusion is that the model in weakalign follows the pipeline of affine first and then TPS in the training procedure. Will it cause any problem if we use a different order in testing step?

Thanks again for your careful clarification.
Rui

**Comment by ignacio-rocco** [comment]
Hi again,

During training the affine and TPS models are treated independently, and are only combined during inference. 

Best,
Ignacio

**Comment by nbei** [comment]
Thanks for your clarification and I will close this issue.
