### ISSUE TITLE
where's "best_aug_resnet_pascal_random_smallerlr_new_strong_50_pascal_affine_resnet101_grid_loss.pth.tar"?

### ISSUE THREAD

**Issue by carlblocking** [ignacio-rocco/weakalign#2]
I tried to use train_weak_pf_pascal.sh, however, "best_aug_resnet_pascal_random_smallerlr_new_strong_50_pascal_affine_resnet101_grid_loss.pth.tar" is not found, how can i find it ?

**Comment by ignacio-rocco** [comment]
First you need a model pretrained using strong supervision. You can use the models linked in the README for this if you don't want to retrain it yourself.

Eg.
Use http://www.di.ens.fr/willow/research/weakalign/trained_models/cnngeo_resnet101_affine.pth.tar
