### ISSUE TITLE
downloaded models cannot be unzipped

### ISSUE THREAD

**Issue by renjiaoyi** [ignacio-rocco/weakalign#3]
I downloaded weakalign_resnet101_affine_tps.pth.tar and cnngeo_resnet101_affine.pth.tar, and both of them cannot be unzipped (or un-tar) by WinRar in windows or using "tar -xvf ..." in Linux, both of them give a message that the file is not in Tar format or damaged, could you please check why it happened?

**Comment by ignacio-rocco** [comment]
You don't need to unzip them, you can load them directly from the code.
Please tell me if this works for you.

Le mar. 29 mai 2018 21:51, littlekoala01 <notifications@github.com> a
écrit :
